### ISSUE TITLE
'develop' cmd not working for me (ZSH)

### ISSUE THREAD

**Issue by sybaz** [TheDiveO/ThirdFlow#10]
Not sure if this is my own issue or a ZSH thing, but the 'develop' cmd isn't being recognized...

Note: 
I have tiddlywiki installed globally, and I also have:
'export PATH="$PATH:./node_modules/.bin' included in my .zshrc file.  

Advise much appreciated...

**Comment by TheDiveO** [comment]
Unfortunately, I have to experience on zsh. The develop shell script has a /bin/sh shebang anyway, so it will be executed in a Bourne shell or a Bash (then in Bourne compatibility mode). Make sure that the script is executable, and that you invoke it directly, that is "./develop"
