### ISSUE TITLE
Add build option to release plugin in unpacked form

### ISSUE THREAD

**Issue by garu57** [TheDiveO/ThirdFlow#12]
First of all thank you for this awesome plugin.
It's indeed the best plugin development guide i found.
Using your guidance, the skeletons and the ui, in half an hour i was able to setup the development env and understand what developing a plugin is about.
I think this should deserve a mention of honor in the official doc.

Anyhow i'm writing to ask if you could add a build option to release the plugin also in unpacked form, complete of `plugin.info`.

Thanks again
Gabriele

**Comment by TheDiveO** [comment]
Gabriele, what do you mean with "unpacked form"? What files (elements) would this unpacked form compromise?

**Comment by garu57** [comment]
I know that "unpacked" may be not the exact name but what i mean is that, as far as i understood up to now, plugins may have two forms:
* single json tiddler containing all the tiddlers and whatever else is composing the plugin, exactly in packed form
* plugin folder containing `plugin.info` describing it and all the tiddlers as single files, exactly in unpacked form, as described in [TiddlyWikiFolders](https://tiddlywiki.com/#TiddlyWikiFolders) and [PluginFolders](https://tiddlywiki.com/#PluginFolders)

Which i guess would mean taking all the tiddlers that you select to build the json plugin tiddler and copying them instead as single tiddler files maintaining their directory structure, then generating the meta data `plugin.info`. Like the format of the plugins in `plugins/tiddlywiki` of TiddlyWiki distribution.

I'd like to help with this but this is my first exposure to javaScript and i lack the competences.
I'm still struggling to understand what kind of beast i have got in my hands.
