### ISSUE TITLE
Update to Tiddlywiki 5.1.20

### ISSUE THREAD

**Issue by kookma** [TheDiveO/ThirdFlow#14]
This is not an issue but a request!
Thirdflow makes plugin development quite easy and straightforward!
It worth to update to latest Tiddlywiki and use the new features of TW 5.1.20

Thank  you for this great a piece of work: ThirdFlow

**Comment by TheDiveO** [comment]
Updated to TW Core 5.1.20 and fixed codemirror plugin references. TF doesn't yet make use of any new TW features though.

**Comment by kookma** [comment]
@TheDiveO 

Many thanks! TF is the main tool for my newly created plugins!
Hope when you had time optimize and furnish TF with 5.1.20 new features.

Highly appreciated your time and talent
