### ISSUE TITLE
Use custom port number

### ISSUE THREAD

**Issue by kookma** [TheDiveO/ThirdFlow#15]
Thirdflow by default uses 8080 port.
Sometimes you have opened another wiki from node.js which occupies 8080 port.
How is it possible to run thirdflow as below 

`npm run develop portn`

where _portn_ is a port number like 8080 or 8050, etc

**Comment by TheDiveO** [comment]
At the moment, you have to adjust the `package.json` locally on your system. When you open `package.json` you'll find two lines, one for unix and one for Windows:

```json
   ...
    "winstart": "start \"ThirdFlow Develop\" cmd /c tiddlywiki editions/develop --verbose --server 8080 $:/core/save/all text/plain text/html",
   ...
    "develop": "tiddlywiki editions/develop --verbose --server 8080 $:/core/save/all text/plain text/html",
   ...
```

Adjust the port value `8080` immediately after `--server` according to your needs.

It seems that it is possible to [pass optional args](https://stackoverflow.com/questions/11580961/sending-command-line-arguments-to-npm-script) to `npm run` so I'll try if that actually works.

**Comment by kookma** [comment]
@TheDiveO 
Thanks that works for me!

**Comment by thediveo** [comment]
Added npm config var support in 1.2.11. See `README.md` for details.

**Comment by kookma** [comment]
Thanks. It seems TiddlyWikiPluginSkeleton uses TF 1.2.10.
I followed the instruction to install a local version TiddlyWikiPluginSkeleton
`npm install`

**Comment by kookma** [comment]
I changed the package.json as below

```
  "dependencies": {
    "tiddlywiki": ">=5.1.20",
    "tw5-thirdflow": ">=1.2.11"
  },
```

still no success

**Comment by thediveo** [comment]
`npm update`
