### ISSUE TITLE
Writing 0-byte files

### ISSUE THREAD

**Issue by seneschal2** [TheDiveO/ThirdFlow#8]
My tiddler edits to the Skeleton files are producing 0-byte files.  Perhaps I'm configuring incorrectly but using tw v5.1.9 on node v5.2.0.  Tried on Chrome & FF (w & w/o TiddlyFox enabled).

Not sure if OE but could really use this informal but promising development environment..

**Comment by TheDiveO** [comment]
With the recent updates to ThirdFlow in place I can't reproduce the 0-byte files issue (anymore). I knew that I had seen them at some time way back. But with the recent version I can not only create ordinary tiddlers anew, but also Javascript TW5 modules in tiddlers that have their name ending in .js.
